import { Dimensions } from 'react-native';


const Country_City = [
  { label: "Albania- Tirana", value: "2" },
  { label: "Andorra- Andorra la Vella ", value: "3" },
  { label: "Angola- Luanda ", value: "4" },
  { label: "Anguilla- The valley ", value: "5" },
  { label: "Argentina- Buenos Aires ", value: "6" },
  { label: "Armenia- Yerevan ", value: "7" },
  { label: "Aruba- Oranjestad ", value: "8" },
  { label: "Australia- Canberra", value: "9" },
  { label: "Australia- Sydney ", value: "10" },
  { label: "Australia- Melbourne", value: "11" },
  { label: "Austria- Vienna ", value: "12" },
  { label: "Azerbaijan- Baku Baki ", value: "13" },
  { label: "Bangladesh- Dacca ", value: "14" },
  { label: "Barbados- Bridgetown ", value: "15" },
  { label: "Belarus- Minsk ", value: "16" },
  { label: "Belgium- Bruxelles ", value: "17" },
  { label: "Belize- Belmopan ", value: "18" },
  { label: "Benin- Porto Novo ", value: "19" },
  { label: "Bolivia- Sucre ", value: "20" },
  { label: "Bosnia and Herzegovina- Sarajevo ", value: "21" },
  { label: "Botswana- Gaborone ", value: "22" },
  { label: "Brazil- Rio De Janeiro ", value: "23" },
  { label: "Bulgaria- Sofia ", value: "24" },
  { label: "Bulgaria- Varna", value: "25" },
  { label: "Bulgaria- Plovdiv", value: "26" },
  { label: "Bulgaria- Burgas", value: "27" },
  { label: "Cambodia- Phnom Penh ", value: "28" },
  { label: "Canada- Ottawa", value: "29" },
  { label: "Chile- Santiago del Chile ", value: "30" },
  { label: "China- Beijing ", value: "31" },
  { label: "Colombia- Bogotá", value: "32" },
  { label: "Colombia- Cali", value: "33" },
  { label: "Costa rica- San José ", value: "34" },
  { label: "Cote d'ivoire- Yamoussoukro ", value: "35" },
  { label: "Croatia- Zagabria ", value: "36" },
  { label: "Cuba- Havana ", value: "37" },
  { label: "Cyprus- Nicosia ", value: "38" },
  { label: "Czech republic- Prague", value: "39" },
  { label: "Denmark- Copenaghen ", value: "40" },
  { label: "Djibouti- Gibuti ", value: "41" },
  { label: "Dominica- Roseau ", value: "42" },
  { label: "Dominican republic- Santo Domingo ", value: "43" },
  { label: "United Kingdom- London ", value: "44" },
  { label: "United Kingdom- Manchester", value: "45" },
  { label: "United Kingdom- Liverpool", value: "46" },
  { label: "United Kingdom- Burnley", value: "47" },
  { label: "Ecuador- uito ", value: "48" },
  { label: "Egypt- Cairo ", value: "49" },
  { label: "salvador- Dipartimento di San Salvador ", value: "50" },
  { label: "Eritrea- Asmara ", value: "51" },
  { label: "Estonia- Tallinn ", value: "52" },
  { label: "Finland- Helsinki ", value: "53" },
  { label: "Philippines- Quezon City", value: "54" },
  { label: "France- Paris", value: "55" },
  { label: "Gambia- Banjul", value: "56" },
  { label: "Georgia- Tbilisi ", value: "57" },
  { label: "Germany- Berlin", value: "58" },
  { label: "Germany- Frankfurt ", value: "59" },
  { label: "Gibraltar- Gibilterra", value: "60" },
  { label: "Greece- Athens ", value: "61" },
  { label: "Greenland- Nuuk ", value: "62" },
  { label: "Grenada- Saint George's ", value: "63" },
  { label: "Guam- Hagåtña ", value: "64" },
  { label: "Guatemala- City of Guatemala ", value: "65" },
  { label: "Guyana- Georgetown ", value: "66" },
  { label: "Holy see- City of Vatican ", value: "67" },
  { label: "Hong konng- Hong Kong ", value: "68" },
  { label: "Hungary- Budapest ", value: "69" },
  { label: "Iceland- Reykjavík ", value: "70" },
  { label: "India- New Delhi ", value: "71" },
  { label: "Indonesia- Giacarta ", value: "72" },
  { label: "Irland- Dublin ", value: "73" },
  { label: "Israel- Gerusalem ", value: "74" },
  { label: "Italy- Rome", value: "75" },
  { label: "Italy- Milan", value: "76" },
  { label: "Jamaica- Kingston ", value: "77" },
  { label: "Japan- Tokyo", value: "78" },
  { label: "Kazakhstan- Astana ", value: "79" },
  { label: "Corea North- yongyang ", value: "80" },
  { label: "South korea- Seul ", value: "81" },
  { label: "Kuwait- Madinat al-Kuwait ", value: "82" },
  { label: "Kyrgyzstan- Bishkek ", value: "83" },
  { label: "Latvia- Riga ", value: "84" },
  { label: "Lebanon- Beirut ", value: "85" },
  { label: "Lesotho- Maseru ", value: "86" },
  { label: "Liechtenstein- Vaduz ", value: "87" },
  { label: "Lithuania- Vilnius ", value: "88" },
  { label: "Luxembourg- Luxembourg City ", value: "89" },
  { label: "Macao- Macau ", value: "90" },
  { label: "Macedonia- Skopje ", value: "91" },
  { label: "Malaysia- Kuala Lumpur ", value: "92" },
  { label: "Mali- Bamako ", value: "93" },
  { label: "Malta- La Valletta ", value: "94" },
  { label: "Mauritania- Nouakchott ", value: "95" },
  { label: "Mauritius- Port Louis ", value: "96" },
  { label: "Mayotte- Mamoudzou ", value: "97" },
  { label: "Mexico- Mexico City ", value: "98" },
  { label: "Micronesia- Palikir ", value: "99" },
  { label: "Moldova- Chișinău ", value: "100" },
  { label: "Monaco- Monte Carlo ", value: "101" },
  { label: "Mongolia- Ulan Bator ", value: "102" },
  { label: "Montenegro- Podgorica ", value: "103" },
  { label: "Morocco- Rabat ", value: "104" },
  { label: "Namibia- Windhoek ", value: "105" },
  { label: "Nauru- Yaren ", value: "106" },
  { label: "Netherlands- Amsterdam ", value: "107" },
  { label: "Netherlands Antilles- Willemstad ", value: "108" },
  { label: "New Caledonia- Nouméa ", value: "109" },
  { label: "New Zealand- Wellington ", value: "110" },
  { label: "Norway- Olso ", value: "111" },
  { label: "Pakistan- Islamabad ", value: "112" },
  { label: "Palau- Melekeok", value: "113" },
  { label: "Panama- Panamá ", value: "114" },
  { label: "Paraguay- Asunción", value: "115" },
  { label: "Peru- Lima ", value: "116" },
  { label: "philippines- Manila ", value: "117" },
  { label: "Pitcairn- Adamstown", value: "118" },
  { label: "Poland- Varsavia", value: "119" },
  { label: "Portugal- Lisbona ", value: "120" },
  { label: "Puerto Rico- San Juan ", value: "121" },
  { label: "Romania- Bucarest ", value: "122" },
  { label: "Russian Federation - Moscow ", value: "123" },
  { label: "San Marino- San Marino ", value: "124" },
  { label: "Singapore- Singapore ", value: "125" },
  { label: "Slovakia- Bratislava ", value: "16" },
  { label: "Slovenia- Lubiana ", value: "17" },
  { label: "Spain- Madrid ", value: "128" },
  { label: "Spain- Barcelona ", value: "129" },
  { label: "Sri Lanka- Colombo ", value: "130" },
  { label: "Sweden- Stockholm ", value: "131" },
  { label: "Switzerland- Bern ", value: "132" },
  { label: "Taiwan- Taipei ", value: "133" },
  { label: "Thailand- Bangkok ", value: "134" },
  { label: "Turkey- Ankara ", value: "135" },
  { label: "Turkey- Istambul", value: "136" },
  { label: "Ukraine- Kiev ", value: "137" },
  { label: "United Arab Emirates- Abu Dhabi ", value: "138" },
  { label: "United States- Washington ", value: "139" },
  { label: "United States- New York City", value: "140" },
  { label: "United States- Irvine- California ", value: "141" },
  { label: "United States- San Jose -California ", value: "142" },
  { label: "United States- Columbus -San Francisco ", value: "143" },
  { label: "Uruguay- Montevideo ", value: "144" },
  { label: "Uzbekistan- Tashkent", value: "145" },
  { label: "Venezuela- Caracas", value: "146" },

]

const PhoneList = [
    { value: "44", label: "UK (+44)"},
	  { value: "1", label: "USA (+1)"},
		{ value: "213", label: "Algeria (+213)"},
		{ value: "376", label: "Andorra (+376)"},
		{ value: "244", label: "Angola (+244)"},
		{ value: "1264", label: "Anguilla (+1264)"},
    { value: "54", label: "Argentina (+54)"},
		{ value: "374", label: "Armenia (+374)"},
		{ value: "297", label: "Aruba (+297)"},
		{ value: "61", label: "Australia (+61)"},
		{ value: "43", label: "Austria (+43)"},
		{ value: "994", label: "Azerbaijan (+994)"},
		{ value: "1242", label: "Bahamas (+1242)"},
		{ value: "973", label: "Bahrain (+973)"},
		{ value: "880", label: "Bangladesh (+880)"},
		{ value: "1246", label: "Barbados (+1246)"},
		{ value: "375", label: "Belarus (+375)"},
		{ value: "32", label: "Belgium (+32)"},
		{ value: "501", label: "Belize (+501)"},
		{ value: "229", label: "Benin (+229)"},
		{ value: "1441", label: "Bermuda (+1441)"},
		{ value: "975", label: "Bhutan (+975)"},
		{ value: "591", label: "Bolivia (+591)"},
		{ value: "387", label: "Bosnia Herzegovina (+387)"},
		{ value: "267", label: "Botswana (+267)"},
		{ value: "55", label: "Brazil (+55)"},
		{ value: "673", label: "Brunei (+673)"},
		{ value: "359", label: "Bulgaria (+359)"},
    { value: "1", label: "Canada (+1)"},
    { value: "56", label: "Chile (+56)"},
		{ value: "86", label: "China (+86)"},
		{ value: "57", label: "Colombia (+57)"},
    { value: "506", label: "Costa Rica (+506)"},
		{ value: "385", label: "Croatia (+385)"},
		{ value: "53", label: "Cuba (+53)"},
		{ value: "90392", label: "Cyprus North (+90392)"},
		{ value: "357", label: "Cyprus South (+357)"},
		{ value: "42", label: "Czech Republic (+42)"},
		{ value: "45", label: "Denmark (+45)"},
		{ value: "253", label: "Djibouti (+253)"},
		{ value: "1809", label: "Dominica (+1809)"},
		{ value: "1809", label: "Dominican Republic (+1809)"},
		{ value: "593", label: "Ecuador (+593)"},
		{ value: "20", label: "Egypt (+20)"},
		{ value: "503", label: "El Salvador (+503)"},
		{ value: "240", label: "Equatorial Guinea (+240)"},
		{ value: "291", label: "Eritrea (+291)"},
		{ value: "372", label: "Estonia (+372)"},
    { value: "358", label: "Finland (+358)"},
		{ value: "33", label: "France (+33)"},
    { value: "7880", label: "Georgia (+7880)"},
		{ value: "49", label: "Germany (+49)"},
    { value: "350", label: "Gibraltar (+350)"},
		{ value: "30", label: "Greece (+30)"},
		{ value: "299", label: "Greenland (+299)"},
		{ value: "1473", label: "Grenada (+1473)"},
		{ value: "590", label: "Guadeloupe (+590)"},
		{ value: "671", label: "Guam (+671)"},
		{ value: "502", label: "Guatemala (+502)"},
    { value: "852", label: "Hong Kong (+852)"},
		{ value: "36", label: "Hungary (+36)"},
		{ value: "354", label: "Iceland (+354)"},
		{ value: "91", label: "India (+91)"},
		{ value: "62", label: "Indonesia (+62)"},
    { value: "353", label: "Ireland (+353)"},
		{ value: "972", label: "Israel (+972)"},
		{ value: "39", label: "Italy (+39)"},
		{ value: "1876", label: "Jamaica (+1876)"},
		{ value: "81", label: "Japan (+81)"},
		{ value: "962", label: "Jordan (+962)"},
		{ value: "7", label: "Kazakhstan (+7)"},
		{ value: "254", label: "Kenya (+254)"},
		{ value: "686", label: "Kiribati (+686)"},
		{ value: "850", label: "Korea North (+850)"},
		{ value: "82", label: "Korea South (+82)"},
		{ value: "965", label: "Kuwait (+965)"},
		{ value: "996", label: "Kyrgyzstan (+996)"},
		{ value: "856", label: "Laos (+856)"},
		{ value: "371", label: "Latvia (+371)"},
		{ value: "961", label: "Lebanon (+961)"},
		{ value: "266", label: "Lesotho (+266)"},
		{ value: "231", label: "Liberia (+231)"},
    { value: "417", label: "Liechtenstein (+417)"},
		{ value: "370", label: "Lithuania (+370)"},
		{ value: "352", label: "Luxembourg (+352)"},
		{ value: "853", label: "Macao (+853)"},
		{ value: "389", label: "Macedonia (+389)"},
		{ value: "261", label: "Madagascar (+261)"},
		{ value: "265", label: "Malawi (+265)"},
		{ value: "60", label: "Malaysia (+60)"},
		{ value: "960", label: "Maldives (+960)"},
		{ value: "223", label: "Mali (+223)"},
		{ value: "356", label: "Malta (+356)"},
    { value: "52", label: "Mexico (+52)"},
		{ value: "691", label: "Micronesia (+691)"},
		{ value: "373", label: "Moldova (+373)"},
		{ value: "377", label: "Monaco (+377)"},
		{ value: "976", label: "Mongolia (+976)"},
    { value: "212", label: "Morocco (+212)"},
		{ value: "258", label: "Mozambique (+258)"},
		{ value: "95", label: "Myanmar (+95)"},
		{ value: "264", label: "Namibia (+264)"},
		{ value: "674", label: "Nauru (+674)"},
		{ value: "977", label: "Nepal (+977)"},
		{ value: "31", label: "Netherlands (+31)"},
		{ value: "687", label: "New Caledonia (+687)"},
		{ value: "64", label: "New Zealand (+64)"},
    { value: "47", label: "Norway (+47)"},
		{ value: "968", label: "Oman (+968)"},
		{ value: "680", label: "Palau (+680)"},
		{ value: "507", label: "Panama (+507)"},
		{ value: "675", label: "Papua New Guinea (+675)"},
		{ value: "595", label: "Paraguay (+595)"},
		{ value: "51", label: "Peru (+51)"},
		{ value: "63", label: "Philippines (+63)"},
		{ value: "48", label: "Poland (+48)"},
		{ value: "351", label: "Portugal (+351)"},
		{ value: "1787", label: "Puerto Rico (+1787)"},
		{ value: "974", label: "Qatar (+974)"},
		{ value: "262", label: "Reunion (+262)"},
		{ value: "40", label: "Romania (+40)"},
		{ value: "7", label: "Russia (+7)"},
		{ value: "250", label: "Rwanda (+250)"},
		{ value: "378", label: "San Marino (+378)"},
    { value: "381", label: "Serbia (+381)"},
		{ value: "248", label: "Seychelles (+248)"},
		{ value: "232", label: "Sierra Leone (+232)"},
		{ value: "65", label: "Singapore (+65)"},
		{ value: "421", label: "Slovak Republic (+421)"},
		{ value: "386", label: "Slovenia (+386)"},
    { value: "34", label: "Spain (+34)"},
		{ value: "94", label: "Sri Lanka (+94)"},
		{ value: "290", label: "St. Helena (+290)"},
		{ value: "1869", label: "St. Kitts (+1869)"},
		{ value: "1758", label: "St. Lucia (+1758)"},
    { value: "268", label: "Swaziland (+268)"},
		{ value: "46", label: "Sweden (+46)"},
		{ value: "41", label: "Switzerland (+41)"},
    { value: "886", label: "Taiwan (+886)"},
		{ value: "7", label: "Tajikstan (+7)"},
		{ value: "66", label: "Thailand (+66)"},
    { value: "216", label: "Tunisia (+216)"},
		{ value: "90", label: "Turkey (+90)"},
		{ value: "7", label: "Turkmenistan (+7)"},
		{ value: "993", label: "Turkmenistan (+993)"},
		{ value: "380", label: "Ukraine (+380)"},
		{ value: "971", label: "United Arab Emirates (+971)"},
		{ value: "598", label: "Uruguay (+598)"},
		{ value: "7", label: "Uzbekistan (+7)"},
		{ value: "678", label: "Vanuatu (+678)"},
		{ value: "379", label: "Vatican City (+379)"},
		{ value: "58", label: "Venezuela (+58)"},
		{ value: "84", label: "Vietnam (+84)"},
    { value: "969", label: "Yemen (North)(+969)"},
    { value: "967", label: "Yemen (South)(+967)"},
]
export default {
  window: {
    width,
    height,
  },
  isSmallDevice: width < 375,
  Country_City: Country_City,
  PhoneList: PhoneList,
  serverUrl: 'http://118.27.9.1/kamata/upload/',
  GoogleMapKey: 'AIzaSyBvfdYMt7Os4kHsigRV9j2Ge7WhhXlX1tc'
};
